import type { Metadata } from 'next';
import '@/app/globals.css';
import NavigationBar from './components/NavigationBar';
import Footer from './components/Footer'; // Ne felejtsd el importálni!
import { GlobalProvider } from './context/GlobalContext';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'DÖKNet',
  description: 'Generated by create next app',
};
//val
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body>
        <GlobalProvider>
          <ToastContainer />
          
          {/* Flexbox wrapper, hogy a lábléc mindig az alján legyen */}
          <div style={{ 
            display: 'flex', 
            flexDirection: 'column', 
            minHeight: '100vh' 
          }}>
            <NavigationBar />
            
            {/* A fő tartalom kitölti a maradék helyet */}
            <main style={{ flex: '1' }}>
              {children}
            </main>

            <Footer />
          </div>
          
        </GlobalProvider>
      </body>
    </html>
  );
}