import type { Metadata } from "next";
import "@/app/globals.css";
import NavigationBar from "./components/NavigationBar";
import { GlobalProvider } from "./context/GlobalContext";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "DÖKNet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <GlobalProvider>
          <ToastContainer />
          <NavigationBar />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
